name: GoldmanTowns
version: ${version}
main: lee.code.towns.Towns
api-version: 1.19
author: Lee
folia-supported: true
depend: [GoldmanColors]
commands:
  towns:
    description: Main towns command.
    permission: towns.command.use
    aliases: [t]
  tc:
    description: Toggle through chat channels.
    permission: towns.command.tc
