name: Towns
version: ${version}
main: lee.code.towns.Towns
api-version: 1.19
author: Lee
folia-supported: true
commands:
  towns:
    description: Main towns command.
    permission: towns.command.use
    aliases: [t]